---
<<<<<<< HEAD:docker-compose.yml
version: "3.7"
=======
# This Docker composition file is used to build and test the container

name: skeleton-docker
>>>>>>> eafe720594319b9503bd5e6d7e5b59e61ff9d6d5:compose.yml

secrets:
  config_json:
    file: ./src/secrets/config.json
  admin_fullchain_pem:
    file: ./src/secrets/admin_fullchain.pem
  admin_privkey_pem:
    file: ./src/secrets/admin_privkey.pem
  phish_fullchain_pem:
    file: ./src/secrets/phish_fullchain.pem
  phish_privkey_pem:
    file: ./src/secrets/phish_privkey.pem

services:
  gophish:
    build:
      # Note build arguments here are for builds using docker-compose (pytest)
      # The CI build workflow uses docker and passes the value from bump_version
      args:
        - VERSION=0.0.8
      context: .
      dockerfile: Dockerfile
<<<<<<< HEAD:docker-compose.yml
    image: cisagov/gophish
    init: true
    restart: always
    ports:
<<<<<<< HEAD
      - target: 3333
        published: 3333
        protocol: tcp
        mode: host
      - target: 8080
        published: 3380
=======
      - target: 8421
        published: 8421
>>>>>>> 0d48ebd47a28a887868ea3093e675e95f3843561
=======
    environment:
      - ECHO_MESSAGE=Hello World from docker compose!
    image: cisagov/example
    init: true
    ports:
      - mode: host
>>>>>>> eafe720594319b9503bd5e6d7e5b59e61ff9d6d5:compose.yml
        protocol: tcp
        published: "8421"
        target: 8421
    restart: "no"
    secrets:
<<<<<<< HEAD:docker-compose.yml
      - source: config_json
        target: config.json
      - source: admin_fullchain_pem
        target: admin_fullchain.pem
      - source: admin_privkey_pem
        target: admin_privkey.pem
      - source: phish_fullchain_pem
        target: phish_fullchain.pem
      - source: phish_privkey_pem
        target: phish_privkey.pem
=======
      - source: quote_txt
        target: quote.txt

  example-version:
    # Run the container to collect version information
    command: --version
    image: cisagov/example
    init: true
    restart: "no"
>>>>>>> eafe720594319b9503bd5e6d7e5b59e61ff9d6d5:compose.yml
